FROM giorgiogrisetti/ubuntu20.04_cuda_ros_noetic_srrg2_solver



# /workspace/ <---- catkin workspace

WORKDIR /
CMD [ "bash" ]

RUN echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc
RUN echo "alias ws2='source /workspace/devel/setup.bash'" >> ~/.bashrc





